-- PRD decision 120. The interview sheets carry a nine-question transcript and
-- per-category notes from each of two interviewers. This is where those go.
--
-- Additive only. No backfill, and no existing row changes meaning:
--   - every existing InterviewResult gets note = NULL and recommendation = NULL,
--     which render nothing at all, and scoreIsComputed = false, which is exactly
--     what every row imported before this migration is — a verbatim average read
--     off the sheet. The default is the honest value, so there is nothing to
--     backfill and no window where a row means something it did not mean before;
--   - every existing InterviewCategoryScore gets note = NULL, likewise rendering
--     nothing;
--   - InterviewQuestion and InterviewAnswer start empty, so every applicant whose
--     notes were imported under the old single-column contract keeps rendering
--     from InterviewNotes.body exactly as they did.
-- So the day this deploys, every screen looks exactly as it did before.
--
-- InterviewNotes is deliberately untouched, including UNIQUE (applicantId). The
-- notes sheet is one shared notetaker's transcript, not a per-interviewer
-- judgement; the per-interviewer prose goes on InterviewResult, which has been
-- keyed (applicantId, interviewerName) since 20260820000000_first_round_interviews.
--
-- Generated by `prisma migrate diff`, then hand-finished below for the one CHECK
-- Prisma cannot express. It is asserted against the database by
-- prisma/checks/interview-transcript.ts.

-- CreateEnum
CREATE TYPE "InterviewRecommendation" AS ENUM ('YES', 'NO');

-- AlterTable
ALTER TABLE "InterviewCategoryScore" ADD COLUMN     "note" TEXT;

-- AlterTable
ALTER TABLE "InterviewResult" ADD COLUMN     "note" TEXT,
ADD COLUMN     "recommendation" "InterviewRecommendation",
ADD COLUMN     "scoreIsComputed" BOOLEAN NOT NULL DEFAULT false;

-- CreateTable
CREATE TABLE "InterviewQuestion" (
    "id" TEXT NOT NULL,
    "instanceId" TEXT NOT NULL,
    "ordinal" INTEGER NOT NULL,
    "prompt" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "InterviewQuestion_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "InterviewAnswer" (
    "id" TEXT NOT NULL,
    "interviewNotesId" TEXT NOT NULL,
    "interviewQuestionId" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "InterviewAnswer_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "InterviewQuestion_instanceId_ordinal_key" ON "InterviewQuestion"("instanceId", "ordinal");

-- CreateIndex
CREATE INDEX "InterviewAnswer_interviewQuestionId_idx" ON "InterviewAnswer"("interviewQuestionId");

-- CreateIndex
CREATE UNIQUE INDEX "InterviewAnswer_interviewNotesId_interviewQuestionId_key" ON "InterviewAnswer"("interviewNotesId", "interviewQuestionId");

-- AddForeignKey
ALTER TABLE "InterviewQuestion" ADD CONSTRAINT "InterviewQuestion_instanceId_fkey" FOREIGN KEY ("instanceId") REFERENCES "Instance"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "InterviewAnswer" ADD CONSTRAINT "InterviewAnswer_interviewNotesId_fkey" FOREIGN KEY ("interviewNotesId") REFERENCES "InterviewNotes"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "InterviewAnswer" ADD CONSTRAINT "InterviewAnswer_interviewQuestionId_fkey" FOREIGN KEY ("interviewQuestionId") REFERENCES "InterviewQuestion"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- ---------------------------------------------------------------------------
-- Hand-written below this line.
-- ---------------------------------------------------------------------------

-- An ordinal is a position in the sheet, counted from the left. A negative one
-- could only come from a arithmetic slip in the commit path, and it would sort
-- the transcript wrongly rather than fail — the questions would render in an
-- order nobody chose, which reads as the interview having gone that way. Cheap
-- to refuse here, invisible if it ever happened.
ALTER TABLE "InterviewQuestion" ADD CONSTRAINT "InterviewQuestion_ordinal_nonneg"
    CHECK ("ordinal" >= 0);

-- Deliberately NOT constrained, recorded so the omission reads as a choice:
--
--   * `InterviewResult.scoreIsComputed` against `score`. There is no invariant
--     between them — any score can legitimately be either computed or verbatim,
--     and the flag records provenance rather than restricting a value.
--   * `InterviewResult.recommendation` against anything. Null is legal and
--     common, and means "this interviewer recorded none" in all three of the
--     ways it can arise (column unmapped, cell blank, value unreadable).
--   * `InterviewCategoryScore.note` against `points`. A note with no score is
--     already impossible: decision 59 writes no row at all for an unreadable
--     score, so there is no row for an orphaned note to live on. The importer
--     reports that case; the database cannot see it.
