-- Phase 1, Slice 1. Brings the schema up to PRD v1.2 §5.
--
-- Hand-written rather than generated, for three reasons `prisma migrate diff`
-- cannot cover: the groupKey backfill, the two CHECK constraints (Prisma has no
-- syntax for them), and the AuditLog foreign-key change.
--
-- ORDER IS LOAD-BEARING. Sections 3 and 4 read Field.groupKey; section 5 drops
-- it. Moving the drop earlier silently discards every existing grouping,
-- because the DROP would succeed and the backfill would then match zero rows.

-- ---------------------------------------------------------------------------
-- 1. New enum
-- ---------------------------------------------------------------------------

CREATE TYPE "FieldGroupRole" AS ENUM ('OPTION', 'FREE_TEXT');

-- ---------------------------------------------------------------------------
-- 2. FieldGroup and ImportRow
-- ---------------------------------------------------------------------------

CREATE TABLE "FieldGroup" (
    "id" TEXT NOT NULL,
    "instanceId" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "displayName" TEXT NOT NULL,
    "category" "FieldCategory" NOT NULL,
    "isMultiSelect" BOOLEAN NOT NULL DEFAULT false,
    "isIncluded" BOOLEAN NOT NULL DEFAULT true,
    "ordinal" INTEGER NOT NULL,
    "visibleToWrittenReviewer" BOOLEAN,
    "visibleToFirstRoundReviewer" BOOLEAN,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "FieldGroup_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "FieldGroup_instanceId_key_key" ON "FieldGroup"("instanceId", "key");
CREATE INDEX "FieldGroup_instanceId_ordinal_idx" ON "FieldGroup"("instanceId", "ordinal");

ALTER TABLE "FieldGroup" ADD CONSTRAINT "FieldGroup_instanceId_fkey"
    FOREIGN KEY ("instanceId") REFERENCES "Instance"("id") ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE "ImportRow" (
    "id" TEXT NOT NULL,
    "instanceId" TEXT NOT NULL,
    "rowIndex" INTEGER NOT NULL,
    "cells" JSONB NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ImportRow_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "ImportRow_instanceId_rowIndex_key" ON "ImportRow"("instanceId", "rowIndex");

ALTER TABLE "ImportRow" ADD CONSTRAINT "ImportRow_instanceId_fkey"
    FOREIGN KEY ("instanceId") REFERENCES "Instance"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- ---------------------------------------------------------------------------
-- 3. Field gains groupId and groupRole
--
--    Added nullable and left empty here. Section 4 populates them, and only
--    then does section 5 remove the column they are derived from.
-- ---------------------------------------------------------------------------

ALTER TABLE "Field" ADD COLUMN "groupId" TEXT;
ALTER TABLE "Field" ADD COLUMN "groupRole" "FieldGroupRole";

ALTER TABLE "Field" ADD CONSTRAINT "Field_groupId_fkey"
    FOREIGN KEY ("groupId") REFERENCES "FieldGroup"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- ---------------------------------------------------------------------------
-- 4. BACKFILL — reads Field.groupKey, which still exists at this point
--
--    Without this the migration would be a silent data loss: every column that
--    carried groupKey = 'ethnicity' would come out the far side ungrouped, the
--    §10.7 demographic breakdown would have no group to read, and nothing would
--    report an error. An existing dev database keeps its grouping instead.
--
--    key AND displayName both take the old groupKey verbatim. key is immutable
--    from here (PRD §5), so inventing a prettier one now would freeze a guess;
--    displayName is what the admin renames.
-- ---------------------------------------------------------------------------

INSERT INTO "FieldGroup" (
    "id", "instanceId", "key", "displayName", "category",
    "isMultiSelect", "isIncluded", "ordinal",
    "visibleToWrittenReviewer", "visibleToFirstRoundReviewer",
    "createdAt", "updatedAt"
)
SELECT
    -- Derived, not random, so this INSERT and the UPDATE below agree on the id
    -- without a RETURNING round-trip or a correlated subquery.
    --
    -- NOTE FOR WHOEVER READS THIS TABLE LATER: these ids are 32-char md5 hex,
    -- while rows created afterward get a 25-char cuid from Prisma. Not a type
    -- mismatch — the column is TEXT and @default(cuid()) is generated by the
    -- client, so the database emits no DEFAULT and has no opinion on shape.
    -- But FieldGroup.id genuinely carries more than one shape, and in dev a
    -- third: prisma/seed.ts writes derived ids like "seed_s26_demo_field_00".
    -- Never validate one of these ids by length or pattern.
    md5(f."instanceId" || ':' || f."groupKey"),
    f."instanceId",
    f."groupKey",
    f."groupKey",
    -- Members of a group already share these. Aggregates rather than an
    -- arbitrary row so that legacy data which disagrees resolves predictably.
    (array_agg(f."category" ORDER BY f."ordinal"))[1],
    bool_or(f."isMultiSelect"),
    -- bool_and, not bool_or: if any member was excluded, exclude the group.
    -- A partially excluded group cannot occur under v1.2, and the conservative
    -- reading is the one that cannot leak a column onto a review surface.
    bool_and(f."isIncluded"),
    min(f."ordinal"),
    (array_agg(f."visibleToWrittenReviewer" ORDER BY f."ordinal"))[1],
    (array_agg(f."visibleToFirstRoundReviewer" ORDER BY f."ordinal"))[1],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM "Field" f
WHERE f."groupKey" IS NOT NULL
GROUP BY f."instanceId", f."groupKey";

UPDATE "Field" f
SET "groupId"   = md5(f."instanceId" || ':' || f."groupKey"),
    -- Every pre-v1.2 group member was a one-hot option. The FREE_TEXT role did
    -- not exist, and the seed deliberately kept the write-in outside the group,
    -- so there is no member that should become FREE_TEXT here. Slice 1 moves
    -- the write-in in via the seed, not via this migration.
    "groupRole" = 'OPTION'
WHERE f."groupKey" IS NOT NULL;

-- ---------------------------------------------------------------------------
-- 5. Retire the old columns — only now that section 4 has read them
-- ---------------------------------------------------------------------------

DROP INDEX "Field_instanceId_groupKey_idx";
ALTER TABLE "Field" DROP COLUMN "groupKey";
ALTER TABLE "Field" DROP COLUMN "isMultiSelect";

CREATE INDEX "Field_groupId_idx" ON "Field"("groupId");

-- ---------------------------------------------------------------------------
-- 6. Instance import state
-- ---------------------------------------------------------------------------

ALTER TABLE "Instance" ADD COLUMN "importCommittedAt" TIMESTAMP(3);
ALTER TABLE "Instance" ADD COLUMN "importProposals" JSONB;

-- ---------------------------------------------------------------------------
-- 7. AuditLog: ALTER the constraint, do not rebuild the table
--
--    Postgres has no "ALTER CONSTRAINT ... ON DELETE" for a foreign key, so the
--    action is changed by dropping and re-adding THE CONSTRAINT. The table is
--    never dropped, renamed, recreated or copied, and no row is touched: this
--    is a catalog change against the live table. Rebuilding the table instead
--    would discard the audit history it exists to preserve, which would be a
--    perverse way to fix an auditing bug.
--
--    Cascade is wrong here because deleting an instance destroys the row that
--    records the deletion. See PRD §8 and open decision 14.
-- ---------------------------------------------------------------------------

ALTER TABLE "AuditLog" DROP CONSTRAINT "AuditLog_instanceId_fkey";
ALTER TABLE "AuditLog" ALTER COLUMN "instanceId" DROP NOT NULL;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_instanceId_fkey"
    FOREIGN KEY ("instanceId") REFERENCES "Instance"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- ---------------------------------------------------------------------------
-- 8. CHECK constraints
--
--    Prisma has no syntax for CHECK, so these are invisible in schema.prisma
--    and `prisma migrate dev` will not recreate them if they are ever dropped.
--    prisma/checks/field-groups.ts asserts both against a live database and is
--    the only thing that will notice their absence. Re-run it after any
--    schema change; it is not part of `npm run verify` because it needs a
--    seeded database and writes to it.
--
--    Added last so the section 4 backfill is already consistent with them.
-- ---------------------------------------------------------------------------

-- "set only when groupId is set" (PRD §5), as a database guarantee.
ALTER TABLE "Field" ADD CONSTRAINT "Field_groupRole_iff_groupId"
    CHECK (("groupId" IS NULL) = ("groupRole" IS NULL));

-- Proposals are cleared at commit. Clearing them is one line in the commit
-- transaction, and a refactor can drop a line; stale proposals on a committed
-- instance would read as meaningful to a successor and could contradict the
-- FieldGroup rows beside them.
ALTER TABLE "Instance" ADD CONSTRAINT "Instance_importProposals_cleared_at_commit"
    CHECK ("importCommittedAt" IS NULL OR "importProposals" IS NULL);
