-- PRD decision 119. Class standing, derived at render time from a designated
-- graduation-date column and the cycle's current semester. Nothing about class
-- standing itself is stored; these are its two inputs.
--
-- Additive only. No backfill, and no existing row changes meaning:
--   - every existing Field gets isGraduationDate = false, i.e. "not designated",
--     which renders no class standing line at all;
--   - every existing Instance gets a NULL semester, which also renders no line
--     until an admin uses the one set-once control on the settings page.
-- So the day this deploys, every screen looks exactly as it did before.
--
-- Generated by `prisma migrate diff`, then hand-finished below for the two CHECKs
-- on Instance and the partial index and CHECK on Field. Prisma can express none
-- of them. All four are asserted against the database by prisma/checks/.

-- CreateEnum
CREATE TYPE "TermSeason" AS ENUM ('SPRING', 'FALL');

-- AlterTable
ALTER TABLE "Field" ADD COLUMN     "isGraduationDate" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "Instance" ADD COLUMN     "currentTermSeason" "TermSeason",
ADD COLUMN     "currentTermYear" INTEGER;

-- ---------------------------------------------------------------------------
-- Hand-written below this line.
-- ---------------------------------------------------------------------------

-- A half-set semester is not a semester. Both columns are written by one action
-- in one statement, so this should never fire. It exists so that a future
-- refactor writing them separately fails loudly instead of leaving an instance
-- whose class standing silently never appears.
ALTER TABLE "Instance" ADD CONSTRAINT "Instance_currentTerm_both_or_neither"
    CHECK (("currentTermSeason" IS NULL) = ("currentTermYear" IS NULL));

-- Bounds, not validation. The creation form and the set-once action validate the
-- year properly. This catches the value that got past them, such as a two-digit
-- "26", which would otherwise put every applicant ~4000 semesters out and read
-- the whole pool Non-standard. The semester is immutable once written, so a bad
-- value here could only be fixed by deleting the instance: this is the last cheap
-- place to refuse one.
ALTER TABLE "Instance" ADD CONSTRAINT "Instance_currentTermYear_range"
    CHECK ("currentTermYear" IS NULL OR "currentTermYear" BETWEEN 2000 AND 2100);

-- At most one graduation-date column per instance. Two would make class standing
-- ambiguous: the applicant view would have to pick one silently. Partial, so the
-- many `false` rows do not collide, and the same shape as the EMAIL promotion
-- index in 20260809180000_promoted_columns.
CREATE UNIQUE INDEX "Field_instanceId_graduationDate_key"
    ON "Field"("instanceId") WHERE "isGraduationDate" = true;

-- A promoted column cannot also be the graduation date. Its Field row is deleted
-- at FR-3 commit, when its value becomes Applicant.email or displayName, and the
-- designation would be deleted with it. That would leave an instance that was
-- configured for class standing and silently shows none.
ALTER TABLE "Field" ADD CONSTRAINT "Field_graduationDate_not_promoted"
    CHECK (NOT ("isGraduationDate" AND "promotedRole" IS NOT NULL));
